<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Магазин - Главная</title>
    <link rel="stylesheet" href="css/table.css">
    <style>
        a {
            outline: none;
            text-decoration: none;
            display: inline-block;
            width: 19.5%;
            margin-right: 0.625%;
            text-align: center;
            line-height: 3;
            color: #ffffff;
        }

        li:last-child a {
            margin-right: 0;
        }

        a:link, a:visited, a:focus {
            background: darkcyan;
        }

        a:hover {
            background: darkturquoise;
        }

        a:active {
            background: greenyellow;
            color: black;
        }
        body{
            display: flex;
            padding-left: 100px;
            padding-right: 100px;
            padding-top: 50px;
            background: #9bb5e5;
        }
    </style>
</head>
<body>
<a href="acceptance">Приемки</a><br><br>
<a href="buyer">Покупатели</a><br><br>
<a href="order">Заказы</a><br><br>
<a href="product">Продукты</a><br><br>
<a href="returns">Возвраты</a><br><br>
<a href="revaluation_act">Акты переоценки</a><br><br>
<a href="stock">Склады</a><br><br>
<a href="store">Магазины</a><br><br>
</body>

</html>
